### ISSUE TITLE
Error in invalid PC handling

### ISSUE THREAD

**Issue by jchoi2022** [KAIST-IS521/backdoor-DaramG#1]
stepVMContext() is considering <Total instr #> as a valid PC (where program execution exited normally), but I think this is not specified in document.
As a result, your interpreter does not raise an error when single-lined program "jump 1" is given as input. This violates the spec of 'jump' instruction.

**Comment by DaramG** [comment]
Hmm.. I thought about how to handle when PC becomes next of last instruction.
My answer was that it just ends without error. So I implemented it like that.
With your issue, my answer is changed that it should occurs error.
Thanks!
